############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
parent = "About"
name = "Our Podcast Series"
url = "/about/"
weight = 1

[[main]]
parent = "About"
name = "Financial Info"
url = "/about/financials/"
weight = 3

[[main]]
parent = "About"
name = "Code of Conduct"
url = "/about/conduct/"
weight = 4

[[main]]
parent = "About"
name = "Python Software Foundation"
url = "/about/psf/"
weight = 5

[[main]]
parent = "About"
name = "Disclosure Statement"
url = "/about/disclosures/"
weight = 6

[[main]]
name = "Episodes"
url = "/episodes/"
weight = 3

[[main]]
name = "Speakers"
url = "/speakers/"
weight = 4

[[main]]
name = "Blog"
url = "/blog/"
weight = 5

[[main]]
name = "Our Team"
url = "/hosts/"
weight = 6

[[main]]
name = "Handbook"
url = "/about/process/"
weight = 7

[[main]]
name = "Donate"
url = "https://opencollective.com/pypodcats"
weight = 8

[[main]]
name = "Contact"
url = "/contact/"
weight = 9

# footer menu (unused by the Popular theme; footer links are configured via
# params.footer.columns in config/_default/params.toml)
