############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
hasChildren = true

[[main]]
parent = "About"
name = "Our Podcast Series"
url = "about/"
weight = 1

[[main]]
parent = "About"
name = "Our Process"
url = "about/process"
weight =2

[[main]]
parent = "About"
name = "Financial Info"
url = "about/financials"
weight =3

[[main]]
parent = "About"
name = "Code of Conduct"
url = "about/conduct"
weight = 4

[[main]]
parent = "About"
name = "Python Software Foundation"
url = "about/psf"
weight = 5


[[main]]
 name = "Episodes"
 url = "episodes/"
 weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 8

[[main]]
name = "Our Team"
url = "hosts/"
weight = 6

 [[main]]
 name = "Speakers"
 url = "speakers/"
 weight = 4

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact Us"
url = "contact/"
weight = 2

[[footer]]
name = "Code of Conduct"
url = "about/conduct"
weight = 3

[[footer]]
name = "Python Software Foundation"
url = "about/psf"
weight = 3
