############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

 [[main]]
 name = "Episodes"
 url = "episodes/"
 weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 8

[[main]]
name = "Our Team"
url = "hosts/"
weight = 6

# [[main]]
# name = "Speakers"
# url = "speakers/"
# weight = 4

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Contact Us"
url = "contact/"
weight = 2

[[footer]]
name = "Code of Conduct"
url = "conduct/"
weight = 3

